version : "3.8"
services:
  db:
    image: mongo:latest
    ports:
      - 27017:27017
  server:
    build: ./server
    ports:
      - 5200:5200
    restart: always
    links:
      - db
  client:
    build: ./client
    ports:
      - 4200:4200
