version: '3.0'

services:
  client:
    hostname: localhost
    build: ./server
    ports:
      - 80:80
  server:
    build: ./client
    ports:
      - 5200:5200
    links:
      - db
  db:
    image: mongo
    ports: 
      - 27017:27017
